package main

var manualCityMapping = map[string]string{
	"Example Town":        "",
	"Global":              "",
	"Europe":              "",
	"-":                   "",
	"Luxemburg":           "Luxembourg",
	"Duesseldorf":         "Dusseldorf",
	"St.Petersburg":       "St. Petersburg",
	"Nürnberg":            "Stein bei Nürnberg",
	"Silicon Valley":      "San Francisco",
	"Kiev":                "Kyiv",
	"Washington DC":       "Washington",
	"Swaziland":           "Mbabane",
	"New York City":       "New York",
	"Metro Manila":        "Manila",
	"Gqeberha":            "Port Elizabeth",
	"Khmelnitsky":         "Khmelnytskyi",
	"North Kansas City":   "Kansas City",
	"Napoli":              "Naples",
	"Thuwal":              "Jeddah",
	"Cuzco":               "Cusco",
	"SAINT-MARTIN":        "Marigot",
	"Taipei City":         "Taipei",
	"Saint Louis":         "St. Louis",
	"BeiJing":             "Beijing",
	"ZhongWei":            "Zhongwei",
	"St. George's":        "St. George",
	"Los Angles":          "Los Angeles",
	"Male'":               "Male",
	"Taiwan":              "",
	"Ekaterinburg":        "Yekaterinburg",
	"Kharkov":             "Kharkiv",
	"Curacao":             "Willemstad",
	"Porto":               "Águas Santas",
	"Oporto":              "Águas Santas",
	"Indonesia":           "Jakarta",
	"Rostov-on-Don":       "Rostov",
	"Mowsow":              "Moscow",
	"GuangZhou":           "Guangzhou",
	"ShangHai":            "Shanghai",
	"Bogata":              "Bogotá",
	"São João de Meriti":  "Rio de Janeiro",
	"Saint-Barthélemy":    "Saint-Barthélemy-d’Anjou",
	"Zaporizhia":          "Zaporizhzhia",
	"Tel-Aviv":            "Tel Aviv-Yafo",
	"Mt Hagen":            "Mount Hagen",
	"Argentina":           "Buenos Aires",
	"Khmelnitskiy":        "Khmelnytskyi",
	"Avers":               "Sankt Gallen",
	"NOUMEA":              "Nouméa",
	"Cyprus":              "Nicosia",
	"Guam":                "Maina",
	"Scotland":            "Edinburgh",
	"Northern Virginia":   "Richmond",
	"Normandy":            "Rouen",
	"Kapolei (Oahu)":      "Kapolei",
	"Ebene":               "Port Louis",
	"Lalitpur":            "Kathmandu",
	"Karaganda":           "Nur-Sultan",
	"Astana":              "Nur-Sultan",
	"La Reunion":          "Saint-Benoît",
	"Petach Tikva":        "Tel Aviv-Yafo",
	"Serbia":              "Belgrade",
	"Western Yorkshire":   "Yorkshire",
	"Silesia":             "Wrocław",
	"Sao José dos Campos": "Campos",
	"Nizhny Novgorod":     "Nizhniy Novgorod",
	"LA PAZ":              "La Paz",
	"Fujairah":            "Al Fujayrah",
	"North of France":     "Paris",
	"Barataria":           "Chaguanas",
	"Port Vila":           "Port-Vila",
	"Ginoza":              "Okinawa",
	"Panama":              "Panama City",
	"Tumon":               "Hagåtña",
	"上海市":                 "Shanghai",
	"Banyumas":            "Bandung",
	"Lages":               "Criciúma",
	"MJC":                 "São Joaquim",
	"Gianyar":             "Denpasar",
	"Cyberjaya":           "Kuala Lumpur",
	"istanbul":            "Istanbul",
	"Киев":                "Kyiv",
	"Ruhr Region":         "Wetter (Ruhr)",
	"Aqaba":               "Al ‘Aqabah",
	"Batam":               "Singapore",
	"Central Java":        "",
	"East Java":           "",
	"honolulu":            "Honolulu",
	"Fez":                 "Fès",
	"Noakhali":            "Dhaka",
	"Хмельницький":        "Khmelnytskyi",
	"Ottawa Gatineau":     "Gatineau",
	"Bozen":               "Bolzano",
	"Ghent":               "Gent",
	"Mangilao":            "Hagåtña",
}
